-- Query 1 : Find the item that has the minimum weight.

SELECT * FROM ITEMS WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- Query 2 : Find the different warehouses in "Pune".

SELECT WAREHOUSES.WNAME FROM WAREHOUSES
JOIN CITIES ON WAREHOUSES.CITY = CITIES.CITY
WHERE CITIES.CITY = 'Pune';

-- Query 3 : Find the details of items ordered by a customer named "Mr. Patil".

SELECT ITEMS.* FROM ITEMS
JOIN ORDERS_ITEMS ON ITEMS.ITEMNO = ORDERS_ITEMS.ITEMNO
JOIN ORDERS ON ORDERS_ITEMS.ONO = ORDERS.ONO
JOIN CUSTOMER ON ORDERS.CNO = CUSTOMER.CNO
WHERE CUSTOMER.CNAME = 'Mr. Patil';

-- Query 4 : Find a Warehouse that has the maximum number of stores.

SELECT WAREHOUSES.WNAME, COUNT(STORES.SID) AS NUM_OF_STORES
FROM WAREHOUSES
LEFT JOIN STORES ON WAREHOUSES.LOCATION = STORES.LOCATION_CITY
GROUP BY WAREHOUSES.WID, WAREHOUSES.WNAME
ORDER BY NUM_OF_STORES DESC
LIMIT 1;

-- Query 5 : Find an item that is ordered for a minimum number of times.
 
SELECT ITEMS.* FROM ITEMS
LEFT JOIN ORDERS_ITEMS ON ITEMS.ITEMNO = ORDERS_ITEMS.ITEMNO
GROUP BY ITEMS.ITEMNO
ORDER BY COUNT(ORDERS_ITEMS.ONO)
LIMIT 1;

-- Query 6 : Find the detailed orders given by each customer.

SELECT CUSTOMER.CNAME, ORDERS.*, ITEMS.DESCRIPTION, ORDERS_ITEMS.ORDERED_QUANTITY FROM CUSTOMER
JOIN ORDERS ON CUSTOMER.CNO = ORDERS.CNO
JOIN ORDERS_ITEMS ON ORDERS.ONO = ORDERS_ITEMS.ONO
JOIN ITEMS ON ORDERS_ITEMS.ITEMNO = ITEMS.ITEMNO;

